name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Create directories
      run: |
        mkdir -p templates static uploads chunks
    
    - name: Build executable
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --clean --noconfirm --add-data "templates;templates" --add-data "static;static" --add-data "uploads;uploads" --add-data "chunks;chunks" --hidden-import channels --hidden-import daphne --hidden-import django --hidden-import SpeechRecognition --hidden-import pydub --hidden-import ffmpeg --hidden-import ffmpeg-python --hidden-import aifc --hidden-import wave --hidden-import audioop --hidden-import array --hidden-import struct gui.py
        mv dist/Transcribe.exe dist/transcribe.exe
    
    - name: Build executable
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --onefile --clean --noconfirm --add-data "templates:templates" --add-data "static:static" --add-data "uploads:uploads" --add-data "chunks:chunks" --hidden-import channels --hidden-import daphne --hidden-import django --hidden-import SpeechRecognition --hidden-import pydub --hidden-import ffmpeg --hidden-import ffmpeg-python --hidden-import aifc --hidden-import wave --hidden-import audioop --hidden-import array --hidden-import struct gui.py
        chmod +x dist/transcribe
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: transcribe-${{ matrix.os }}
        path: dist/transcribe*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/transcribe-windows-latest/transcribe.exe
          artifacts/transcribe-ubuntu-latest/transcribe
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          # Transcribe v${{ github.ref_name }}
          
          ## Features
          - Audio transcription with real-time processing
          - Support for multiple audio formats
          - User-friendly GUI interface
          - Cross-platform support (Windows and Linux)
          
          ## Downloads
          - Windows: transcribe.exe
          - Linux: transcribe (executable)
          
          ## System Requirements
          - Windows 10/11 or Linux (Kali Linux tested)
          - FFmpeg installed (included in the package)
          - 4GB RAM minimum recommended
          - 500MB free disk space
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 